manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: customkbd      # <-- This remote was missing
      url-base: https://github.com/customkbd

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: temper-zmk-shield  # <-- This project was missing
      remote: customkbd
      revision: main

  self:
    path: config
