manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: customkbd
      url-base: https://github.com/customkbd

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: temper-zmk-shield
      remote: customkbd
      revision: master

  self:
    path: config
